version: '3.2'

services:
  db:
    image: alistairfink/side_projects:link_shortener_db
    restart: always
    ports:
      - "5435:5432"
    networks:
      network:
        ipv4_address: 172.25.1.2
    environment:
      POSTGRES_PASSWORD: docker
  backend:
    image: alistairfink/side_projects:link_shortener_backend
    restart: always
    ports:
      - "41695:41692"
    networks:
      - network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  network:
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/16